### ISSUE TITLE
SOCI 400 OL FA 2024 changes

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#1061]
**Which course contains the bug?**  
PSYC 339 OL FA 2024
 
 
**Describe the error and/or your suggestion**  
Activity 4.2: Read Chapter 4 p. 107-122, 133-144 change to:
Activity 4.2: Read Chapter 4 p. 128-138, 151-167

Question 1: change pages 108 & 109 to say pages 122 & 123
 Question 7: change page 118 to say page 136
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=34715&section=5#tabs-tree-start
2. Unit #   4      Topic #  1       Activity#  4.2
 
**Optional: Screenshots**

**Comment by emilyverse** [comment]
this is actually SOCI 400 OL FA 2024

**Comment by chloecwh** [comment]
Hi @emilyverse thanks for creating the issues, I will be resolving them for you today. Since it's within the same course, I've organize your requests and we will use one central issue (this one) for further communication. I've renamed this title for clarifications. I will be creating a checklist so that I can communicate my progress down below. Here are the requests and urls that you've sent in. 

https://github.com/TWUOnline/bug-tracking/issues/1049
Describe the error and/or your suggestion
We need to change the page numbers under the Activity Checklist, as we have an updated textbook.
So Activity 1.3 (pg. 38 in textbook) will change to Activity 1.3 (pg. 37 in textbook).
Activity 1.4 Read Corey, Corey & Corey Chapter 2 (pg. 37-57 only) to Activity 1.4 Read Corey, Corey & Corey Chapter 2 (pg. 38-58 only)

Location of the bug
Please provide a specific link to the page with the error, as well as where the error is on the page:

URL: https://learn.twu.ca/course/view.php?id=34715&section=2#tabs-tree-start
Unit # 1 Topic # Overview Activity# Activity Checklist


https://github.com/TWUOnline/bug-tracking/issues/1050
Activity 1.3: Complete Self-Inventory pg. 38 in your textbook to:
Activity 1.3: Complete Self-Inventory pg. 37 in your textbook

Activity 1.4: Read Corey, Corey & Corey Chapter 2 (p. 37-57) to:
Activity 1.4: Read Corey, Corey & Corey Chapter 2 (p. 38-58)

Location of the bug
Please provide a specific link to the page with the error, as well as where the error is on the page:

URL: https://learn.twu.ca/course/view.php?id=34715&section=2#tabs-tree-start
Unit # 1 Topic # 1 Activity# 1.3 & 1.4

https://github.com/TWUOnline/bug-tracking/issues/1051 
Activity 2.1: Read Chapter 1 (p. 2-18) to
Activity 2.1: Read Chapter 1 (p. 2-20)

and

Activity 2.4: Read Chapter 1 (p. 19-23) to:
Activity 2.4: Read Chapter 1 (p. 20-25)

Location of the bug
Please provide a specific link to the page with the error, as well as where the error is on the page:

URL: https://learn.twu.ca/course/view.php?id=34715&section=3#tabs-tree-start
Unit # 2 Topic # Overview Activity# Activity Checklist

https://github.com/TWUOnline/bug-tracking/issues/1052
Activity 2.1: Read Chapter 1 page 2-20 to:
Activity 2.1: Read Chapter 1 page 2-20

Location of the bug
Please provide a specific link to the page with the error, as well as where the error is on the page:

URL: https://learn.twu.ca/course/view.php?id=34715&section=3#tabs-tree-start
Unit # 2 Topic # 1 Activity# 2.1


https://github.com/TWUOnline/bug-tracking/issues/1053
Activity 2.4: Read Chapter 1 p. 20-25 to:
Activity 2.4: Read Chapter 1 p. 20-25

Location of the bug
Please provide a specific link to the page with the error, as well as where the error is on the page:

URL: https://learn.twu.ca/course/view.php?id=34715&section=3#tabs-tree-start
Unit # 2 Topic # 2 Activity# 2.4

https://github.com/TWUOnline/bug-tracking/issues/1054

Describe the error and/or your suggestion
Change the page numbers from:
Activity 2.6: Complete the Self-Inventory p. 24-32 to:
Activity 2.6: Complete the Self-Inventory p. 25-32

Location of the bug
Please provide a specific link to the page with the error, as well as where the error is on the page:

URL: https://learn.twu.ca/course/view.php?id=34715&section=3#tabs-tree-start
Unit # 2 Topic # 2 Activity# 2.6


https://github.com/TWUOnline/bug-tracking/issues/1055
Change the page numbers:
In this quote:
“Clients are empowered when they are educated about their rights and responsibilities in the therapeutic process.” p. 153
the page number is now p.176 NOT p.153

Question 3, change the page number from 154 to 177

Question 8, change the page number from 171 to 193

Location of the bug
Please provide a specific link to the page with the error, as well as where the error is on the page:

URL: https://learn.twu.ca/course/view.php?id=34715&section=3#tabs-tree-start
Unit # 2 Topic # 3 Activity# 2.7

https://github.com/TWUOnline/bug-tracking/issues/1056

Activity 3.8: Read Chapter 10 pages 365-373 to
Activity 3.8: Read Chapter 10 pages 419-426

and

Activity 3.12: Read Chapter 10 pages 373-393 to
Activity 3.12: Read Chapter 10 pages 426-449

Location of the bug
Please provide a specific link to the page with the error, as well as where the error is on the page:

URL: https://learn.twu.ca/course/view.php?id=34715&section=4#tabs-tree-start
Unit # 3 Topic # Overview Activity# Activity Checklist

https://github.com/TWUOnline/bug-tracking/issues/1057 
Activity 3.1
Question 7: change from 225 to 257
Question 9: change from 226 to 258
Question 9: change from 231 to 263
Question 10: change from 239-273

Activity 3.2
You are more than welcome to complete all of the activities in the textbook, but for this section I invite you to complete the ‘additional cases for your reflection’ on page 219-220 change to:

You are more than welcome to complete all of the activities in the textbook, but for this section I invite you to complete the ‘additional cases for your reflection’ on page 251-252

Location of the bug
Please provide a specific link to the page with the error, as well as where the error is on the page:

URL: https://learn.twu.ca/course/view.php?id=34715&section=4#tabs-tree-start
Unit # 3 Topic # 1 Activity# Activity 3.1 & 3.2

https://github.com/TWUOnline/bug-tracking/issues/1058 

URL: https://learn.twu.ca/course/view.php?id=34715&section=5#tabs-tree-start
Unit # 4 Topic # 1 Activity# 4.2

Activity 3.8: Read Chapter 10 pages 365-373 change to
Activity 3.8: Read Chapter 10 pages 419-426

Activity 3.8
Question 1: Page 368 to page 420

Location of the bug
Please provide a specific link to the page with the error, as well as where the error is on the page:

URL: https://learn.twu.ca/course/view.php?id=34715&section=4#tabs-tree-start
Unit # 3 Topic # 2 Activity# 3.8

https://github.com/TWUOnline/bug-tracking/issues/1059

Activity 3.12: Read Chapter 10 pages 373-393 to
Activity 3.12: Read Chapter 10 pages 426-449

Question 2: change page 375-376 to page 428-429
QUestion 9: change page 392 to page 446

Location of the bug
Please provide a specific link to the page with the error, as well as where the error is on the page:

URL: https://learn.twu.ca/course/view.php?id=34715&section=4#tabs-tree-start
Unit # 3 Topic # 3 Activity# 3.12

https://github.com/TWUOnline/bug-tracking/issues/1060

PSYC 330 OL FA 2024

Describe the error and/or your suggestion
Activity 4.6: Read Chapter 4 p. 122-128 to:
Activity 4.6: Read Chapter 4 p. 122-146

Activity 4.10: Chapter 4, 129-133 to:
Activity 4.10: Chapter 4, 146-169

Location of the bug
Please provide a specific link to the page with the error, as well as where the error is on the page:

https://github.com/TWUOnline/bug-tracking/issues/1061

URL: https://learn.twu.ca/course/view.php?id=34715&section=5#tabs-tree-start
Unit # 4 Topic # Overview Activity# Activity Checklist

Activity 4.2: Read Chapter 4 p. 107-122, 133-144 change to:
Activity 4.2: Read Chapter 4 p. 128-138, 151-167

Question 1: change pages 108 & 109 to say pages 122 & 123
Question 7: change page 118 to say page 136

Location of the bug
Please provide a specific link to the page with the error, as well as where the error is on the page:

https://github.com/TWUOnline/bug-tracking/issues/1062
Activity 4.6: Read Chapter 4 p. 122- 128 to
Activity 4.6: Read Chapter 4 p. 139- 146

Activity 4.6
Question 2: Change the page number of 125 to page 142
Question 4: change the page numbers of 127-128 to pages 144-145

Activity 4.7
Read the case study on page 126 of the text and use the 8 steps for ethical decision making to solve the dilemma.
CHANGE TO
Read the case study on page 144 of the text and use the 8 steps for ethical decision making to solve the dilemma.

Location of the bug
Please provide a specific link to the page with the error, as well as where the error is on the page:

URL: https://learn.twu.ca/course/view.php?id=34715&section=5#tabs-tree-start
Unit # 4 Topic # 2 Activity# 4.6 & 4.7


https://github.com/TWUOnline/bug-tracking/issues/1063
Describe the error and/or your suggestion
Activity 4.10: Read Chapter 4, p.129-133 CHANGE TO
Activity 4.10: Read Chapter 4, p.146-150

Activity 4.10
Question 3 change the page number 131 to the page number 149

Location of the bug
Please provide a specific link to the page with the error, as well as where the error is on the page:

URL: https://learn.twu.ca/course/view.php?id=34715&section=5#tabs-tree-start
Unit # 4 Topic # 3 Activity# 4.10

**Comment by chloecwh** [comment]
- [x] 1.3 change textbook number
- [x] 1.4 change textbook page number
- [x] 2.1 change textbook page number
- [ ] 2.4 change textbook page number
- [ ] 2.6 change textbook page number
- [ ] 2.7 change activity page number
- [ ] 3.8, 3.12 page number #1056 is duplicated from #1058, #1059
- [ ] 3.1 change number - Question 9: change from 226 to 258 - seems like wrong question number, Question 9: change from 231 to 263 - done (https://github.com/TWUOnline/bug-tracking/issues/1057)
- [ ] 3.2 change activity page number
- [ ] 3.8 change activity page number
- [ ] 4.6 change activity page number and question reference number #1060 and #1062 are on the same activity 
- [ ] 4.10 change activity page number #1060 and #1063
- [ ] 4.2 change activity and question page number
- [ ] 4.7 paragraph info

PROD notes: notify ID with the above changes

**Comment by chloecwh** [comment]
@emilyverse completed requests above, need clarification for activity 3.1, see https://github.com/TWUOnline/bug-tracking/issues/1057
