### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by MargMannShull** [TWUOnline/bug-tracking#520]
### Course
Psych 340
### URL
https://learn.twu.ca/course/view.php?id=20392&section=4
### Instructions
- [x] We will need to add Discussion Forum #4 here and in week #5 (Discussion Forum #5) to the graded assignment sections (Assignment 4.3 and Assignment 5.2 (currently, Assignment 5.2 talks about a CASE STUDY ASSIGNMENT - WE NEED TO GET RID OF THAT - THERE IS NO MORE CASE STUDY ASSIGNMENT!).  We will also need to add these two discussion forums to the Assessment Page.
- [x] Discussion Forum #4 - Reflect on your process recording your helping session for the Video/Transcript assignment.  What skills were easy for you to use?  What skills seemed more difficult or felt unnatural?  What did you learn about yourself as you did this assignment?  As you interact with your colleagues in class, you might explore how cultural considerations might impact the application of helping skills.
- [x] Discussion forum #5 - Clients often ask their helpers for information.  Using your text, (chapter 15) how might you decide when it is appropriate to give the client information and when to explore their ideas?  And, what would it be like to tell a client that _you do not know the answer to their question?_ How might not knowing the answer to their their question influence your perception of yourself as a helper and the client's perception of you?

Please upload required files as attachments.

**Comment by kmarjanovic** [comment]
@MargMannShull I've added the Week 4 & 5 discussion forums.  Note these can be added in Moodle (not through GitHub), so feel free to add for future courses if they are missing.
(Turn Editing On (top right) > Add activity or resource (bottom right) > Forum > add details).  
Please check details of the forum (availability)
I've removed the reference to the Case Study in the Unit 5 Overview. (@cmadland the Grav sync is a little slow, so perhaps push tomorrow if we don't see it?)
