### ISSUE TITLE
Production - WRSH 101 - Activity Checklist alerts

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#96]
### Course
WRSH 101
### URL
https://learn.twu.ca/course/view.php?id=10744&section=4

Unis 1, 4, 5
### Instructions

- [x] Unit 1 checklist - formatting is off on Discussion lines (see picture)

![alert-activity-checklist](https://user-images.githubusercontent.com/35148983/67709792-47f8d580-f984-11e9-9354-57040684af40.png)

- [x] Unit 4 checklist plugin not working.

- [ ] Unit 5 checklist needs to be created (check correct activities in unit)

**Comment by rezakh66** [comment]
@cmadland I have completed unit 5 checklist. please double-check if its done properly.

**Comment by kmarjanovic** [comment]
Thank you @rezakh66 !

I've edited some of the alert content, so all good now!
