### ISSUE TITLE
PSYC ADC Bookdown & Moodle Tracking

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#988]
### Instructions

Please check that the Bookdown is properly formatted and the Moodle Shells are created with the [TWU Online Template
](https://learn.twu.ca/course/view.php?id=33023&section=0#tabs-tree-start).

All links should be in Notion: [PSYC ADC Course Links](https://www.notion.so/twuid/PSYC-Adult-Degree-Completion-355dd35773f84d238291fe1d91db5ab4)

I've listed the courses in order of Priority.

#### For Pilot FA 2024: (12 courses)

PSYC 105: Introduction to Psychology (ID: Dave)
- [x] [Initial Bookdown](https://twu-fhss.github.io/psyc105/)
- [ ] Bookdown
- [ ] Moodle Master

PSYC 106: Introduction to Psychology (ID: Dave)
- [x] [Initial Bookdown](https://twu-fhss.github.io/psyc106/)
- [ ] Bookdown
- [x] [ADC Moodle Master](https://learn.twu.ca/course/view.php?id=15775)
- [x] [GX Moodle Master](https://learn.twu.ca/course/view.php?id=30266&section=3#tabs-tree-start)

[PSYC 215: Lifespan Development (ID: Katy)](https://github.com/psyc-adc/psyc215) - Jeff
- [x] Initial Bookdown
- [ ] Bookdown
- [ ] Word doc
- [ ] Moodle Master

[PSYC 301: Theories of Personality(ID: Kelly & Inok)](https://github.com/psyc-adc/psyc301) - Jeff
- [x] Bookdown
- [x] Word doc
- [ ] Moodle Master

[PSYC 305: Abnormal Psychology (ID: Katy)](https://github.com/psyc-adc/psyc305)
- [x] Bookdown
- [x] Word doc
- [ ] Moodle Master

[PSYC 331: Theories of Counselling (ID: Mara)](https://github.com/psyc-adc/psyc331)
- [ ] Bookdown
- [x] Word doc
- [ ] Moodle Master

[PSYC 340: Interpersonal and Helping Skills (ID: Mara)](https://github.com/psyc-adc/psyc340) 
- [ ] Bookdown
- [x] Word doc
- [ ] Moodle Master

SOCI 101: Introduction to Sociology (ID: Kelly & Inok)
- [x] [Initial Bookdown](https://github.com/twu-fhss/soci101/settings/pages#:~:text=https%3A//twu%2Dfhss.github.io/soci101/)
- [x] [Word to edit](https://github.com/TWUOnline/bug-tracking/issues/984#issuecomment-1981730421)
- [ ] Moodle Master

[SOCI 400: Critical Issues in Human Services (ID: Katy)](https://github.com/psyc-adc/soci400) -Jeff
- [x] [Initial Bookdown](https://psyc-adc.github.io/soci400/)
- [x] [Word to edit](https://github.com/psyc-adc/soci400/tree/main/docs/SOCI-400%20Word%20Docs)
- [ ] Moodle Master

[SOCI 221: Sociology of Family](https://github.com/psyc-adc/soci221) -Jeff
- [ ] [Initial Bookdown](https://psyc-adc.github.io/soci221/)
- [ ] [Word doc](https://github.com/psyc-adc/soci221/tree/main/docs/SOCI-221%20Word%20Docs)
- [ ] Moodle Master

[PSYC 254: Brain & Behavior (ID: Mara) ](https://github.com/psyc-adc/psyc254) **new content
- [ ] Bookdown
- [ ] Moodle Master

[UNIV 301: Lifelong Learning Strategies (ID: Natalia)](https://github.com/psyc-adc/univ301) **new content
- [ ] Bookdown
- [ ] Word doc
- [ ] Moodle Master

#### Soft Launch SP 2025 (12 courses)
PSYC 207: Data Analysis (ID: Katy)
- [ ] Bookdown
- [ ] Moodle Master

PSYC 322: Research Methods II (Natalia & Inok)
- [ ] Bookdown
- [x] [Word doc](https://github.com/TWUOnline/bug-tracking/issues/985#issuecomment-2016079475)
- [ ] Moodle Master

PSYC 335: Positive Psychology
- [ ] Bookdown
- [ ] Moodle Master

PSYC 339: Mental Health & Adjustment
- [ ] Bookdown
- [ ] Moodle Master

PSYC 390: Special Topics in Psychology (Practicum) 
- [ ] Bookdown
- [ ] Moodle Master

PSYC 408: History & Systems of Psychology
- [ ] Bookdown
- [ ] Moodle Master

PSYC 411: Psychology & Spiritual Formation
- [ ] Bookdown
- [ ] Moodle Master

PSYC 490: Psychology Capstone
- [ ] Bookdown
- [ ] Moodle Master

SOCI 201: Introduction to Human Services (ID: Mara)
- [ ] Bookdown
- [ ] Moodle Master

SOCI 221: Sociology of Family  (ID: Natalia )
- [ ] Bookdown
- [ ] Moodle Master

SOCI 320: Human Services Practicum 1
- [ ] Bookdown
- [ ] Moodle Master

SOCI 400: Critical Issues in Human Services
- [ ] Bookdown
- [ ] Moodle Master

#### Full Launch FA 2025 (5 courses)
PSYC 201: Research Methods in Psychology I
- [ ] Bookdown
- [ ] Moodle Master

PSYC 431: Career Counselling & Development
- [ ] Bookdown
- [ ] Moodle Master

SOCI 411: Human Services Practicum 2 
- [ ] Bookdown
- [ ] Moodle Master

SOCI 420: Human Services Practicum 3
- [ ] Bookdown
- [ ] Moodle Master

RELS 343: Issues in Contemporary Culture 
- [ ] Bookdown
- [ ] Moodle Master

***To confirm:***
- PSYC 330: Leadership in Organization and Small Groups 
- SOCI 315: Globalization

**Comment by chloecwh** [comment]
Hi @kmarjanovic I've taken a look at the courses for fall 2024. 
7 of them production can start converting from GRAV to word doc or book down for minor revision, 2 courses that are brand new (PSYC 254 and UNIV 301) - will wait for the unit docs. We will comment on the related repo issue when we start and end the process of conversion.

**Comment by chloecwh** [comment]
Hi @Jeff-TWU and @meher-ahmed, please write a note on the related[ repo issue](https://github.com/orgs/psyc-adc/repositories) when you start on a course. There are 7 of them for us to start converting from the arts-master GRAV... potentially onto Quarto!

**Comment by chloecwh** [comment]
I've started on PSYC 340 https://github.com/psyc-adc/psyc340/issues/1#issuecomment-2028353584

**Comment by kmarjanovic** [comment]
I'll close this issue & refer to FA 2025 psyc adc courses when decided.
